version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: restaurant-saas-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 38jSmwhizxzVmWEY
      POSTGRES_DB: restaurant_saas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - restaurant-network

  nginx:
    image: nginx:alpine
    container_name: restaurant-saas-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    restart: always
    networks:
      - restaurant-network

volumes:
  postgres_data:

networks:
  restaurant-network:
    driver: bridge
